2025-05-16 15:33:45,632 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-16 15:33:45,632 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-16 15:33:45,633 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-16 15:33:45,691 [INFO] [MainThread] [root/config.py:61]: Created default config file at C:\Users\zhiyu\.config\yasb\config.yaml
2025-05-16 15:33:45,725 [INFO] [MainThread] [root/config.py:75]: Created default stylesheet at C:\Users\zhiyu\.config\yasb\styles.css
2025-05-16 15:33:53,011 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-16 15:33:58,785 [ERROR] [MainThread] [root/weather.py:168]: API key or location is missing. Please provide a valid API key and location.
2025-05-16 15:33:58,888 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-16 15:34:02,937 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-16 15:34:02,978 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-b90424f0-328c-11f0-81b6-346f24c928cb
2025-05-16 15:34:03,056 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-16 15:34:03,061 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 02:08:06,876 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-19 02:08:06,877 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-19 02:08:06,879 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-19 02:10:19,577 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-19 02:10:23,374 [ERROR] [MainThread] [root/weather.py:168]: API key or location is missing. Please provide a valid API key and location.
2025-05-19 02:10:23,449 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-19 02:10:25,532 [INFO] [Dummy-3] [root/event_listener.py:53]: Created named pipe yasb-f47161d9-3477-11f0-b1e5-346f24c928cb
2025-05-19 02:10:25,532 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-19 02:10:25,599 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-19 02:10:25,600 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 02:10:25,749 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-f47161d9-3477-11f0-b1e5-346f24c928cb
2025-05-19 02:13:25,720 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-19 02:13:25,721 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-19 02:13:25,721 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-19 02:13:25,837 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-19 02:13:25,957 [ERROR] [MainThread] [root/weather.py:168]: API key or location is missing. Please provide a valid API key and location.
2025-05-19 02:13:25,960 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-19 02:13:26,708 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-19 02:13:26,739 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-606edfbf-3478-11f0-b86f-346f24c928cb
2025-05-19 02:13:26,778 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-19 02:13:26,780 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 02:13:26,860 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-606edfbf-3478-11f0-b86f-346f24c928cb
2025-05-19 02:14:46,919 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-19 02:14:46,919 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-19 02:14:46,919 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-19 02:14:47,031 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-19 02:14:47,115 [ERROR] [MainThread] [root/weather.py:168]: API key or location is missing. Please provide a valid API key and location.
2025-05-19 02:14:47,117 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-19 02:14:47,787 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-19 02:14:47,804 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-90c26ebc-3478-11f0-9203-346f24c928cb
2025-05-19 02:14:47,832 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-19 02:14:47,833 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 02:14:47,888 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-90c26ebc-3478-11f0-9203-346f24c928cb
2025-05-19 02:33:03,896 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:249]: CLI server received command: stop
2025-05-19 02:33:03,897 [INFO] [Thread-1 (_run_server)] [root/controller.py:27]: Exiting Application from CLI...
2025-05-19 02:33:04,010 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-19 02:33:04,010 [DEBUG] [Thread-1 (_run_server)] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-19 02:33:04,146 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-19 02:33:04,150 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-19 02:33:04,151 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-19 02:33:04,612 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-19 02:33:04,614 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-19 02:33:04,614 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-19 02:33:05,199 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-19 02:33:06,157 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-19 02:33:07,190 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-19 02:33:07,210 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-200e1eb6-347b-11f0-a97a-346f24c928cb
2025-05-19 02:33:07,255 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-19 02:33:07,258 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 02:33:07,362 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-200e1eb6-347b-11f0-a97a-346f24c928cb
2025-05-19 02:33:07,742 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 02:33:07.741757
2025-05-19 02:33:08,565 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 02:33:08,575 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 02:33:34,270 [WARNING] [Dummy-5] [root/event_listener.py:84]: Pipe has been ended: (109, 'PeekNamedPipe', 'The pipe has been ended.')
2025-05-19 02:33:34,270 [INFO] [Dummy-5] [root/event_listener.py:94]: Attempting to reconnect to Komorebi...
2025-05-19 02:33:37,271 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-200e1eb6-347b-11f0-a97a-346f24c928cb
2025-05-19 02:33:42,466 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-200e1eb6-347b-11f0-a97a-346f24c928cb
2025-05-19 02:37:43,806 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 02:37:43,809 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 02:37:49,353 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 02:37:49,357 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 02:37:57,151 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 02:38:01,064 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 02:43:06,479 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 02:43:06.479286
2025-05-19 02:53:06,542 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 02:53:06.542230
2025-05-19 03:03:06,571 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 03:03:06.571143
2025-05-19 03:13:06,622 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 03:13:06.622580
2025-05-19 03:23:06,460 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 03:23:06.460387
2025-05-19 03:33:06,545 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 03:33:06.545626
2025-05-19 03:38:01,081 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 03:38:01,090 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 03:38:06,096 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 03:38:06,103 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 03:38:13,953 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 03:38:18,856 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 03:43:06,540 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 03:43:06.540300
2025-05-19 03:53:06,563 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 03:53:06.563641
2025-05-19 04:03:06,525 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 04:03:06.525794
2025-05-19 04:13:06,500 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 04:13:06.500380
2025-05-19 04:23:06,477 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 04:23:06.477536
2025-05-19 04:33:06,541 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 04:33:06.541815
2025-05-19 04:38:30,958 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:38:30,961 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:38:37,067 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:38:37,069 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:38:45,804 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:38:52,125 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:43:06,622 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 04:43:06.622563
2025-05-19 04:47:04,178 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-19 04:47:04,282 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-19 04:47:04,282 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-19 04:47:04,303 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-19 04:47:04,315 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-19 04:47:04,317 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-19 04:47:07,149 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-19 04:47:07,149 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-19 04:47:07,150 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-19 04:47:08,906 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-19 04:47:15,300 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-19 04:47:17,959 [INFO] [Dummy-3] [root/event_listener.py:53]: Created named pipe yasb-deafcb04-348d-11f0-8a1b-346f24c928cb
2025-05-19 04:47:17,959 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-19 04:47:18,074 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-19 04:47:18,077 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 04:47:18,551 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 04:47:18.550589
2025-05-19 04:47:19,235 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:47:19,243 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:48:10,374 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-19 04:48:10,480 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-19 04:48:10,480 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-19 04:48:10,490 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-19 04:48:10,496 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-19 04:48:10,497 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-19 04:48:10,799 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-19 04:48:10,800 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-19 04:48:10,800 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-19 04:48:11,310 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-19 04:48:11,907 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-19 04:48:13,101 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-19 04:48:13,102 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-ff8de90b-348d-11f0-b761-346f24c928cb
2025-05-19 04:48:13,169 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-19 04:48:13,170 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 04:48:13,460 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 04:48:13.460550
2025-05-19 04:48:13,767 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:48:13,772 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:52:27,922 [INFO] [MainThread] [root/controller.py:12]: Reloading Application from tray...
2025-05-19 04:52:28,025 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-19 04:52:28,025 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-19 04:52:28,035 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-19 04:52:28,041 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-19 04:52:28,042 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-19 04:52:28,389 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-19 04:52:28,390 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-19 04:52:28,390 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-19 04:52:28,803 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-19 04:52:29,250 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-19 04:52:30,644 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-19 04:52:30,666 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-990ff6cd-348e-11f0-883f-346f24c928cb
2025-05-19 04:52:30,720 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-19 04:52:30,721 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 04:52:31,057 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 04:52:31.057857
2025-05-19 04:52:31,474 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:52:31,531 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:53:02,921 [INFO] [MainThread] [root/controller.py:12]: Reloading Application from tray...
2025-05-19 04:53:03,027 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-19 04:53:03,027 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-19 04:53:03,037 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-19 04:53:03,043 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-19 04:53:03,046 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-19 04:53:03,350 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-19 04:53:03,350 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-19 04:53:03,351 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-19 04:53:03,713 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-19 04:53:04,501 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-19 04:53:05,697 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-19 04:53:05,706 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-adf4a745-348e-11f0-bedf-346f24c928cb
2025-05-19 04:53:05,783 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-19 04:53:05,786 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 04:53:06,123 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 04:53:06.123869
2025-05-19 04:53:06,554 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:53:06,559 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 04:53:11,076 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-adf4a745-348e-11f0-bedf-346f24c928cb
2025-05-19 05:03:04,858 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 05:03:04.858702
2025-05-19 05:13:04,916 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 05:13:04.916199
2025-05-19 05:23:04,910 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 05:23:04.910062
2025-05-19 05:33:04,887 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 05:33:04.887727
2025-05-19 05:38:52,140 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 05:38:52,148 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 05:38:55,418 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 05:38:55,432 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 05:39:04,674 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 05:39:10,442 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 05:43:05,004 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 05:43:05.004361
2025-05-19 05:53:04,823 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 05:53:04.823290
2025-05-19 06:03:04,960 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 06:03:04.954700
2025-05-19 06:13:04,865 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 06:13:04.863853
2025-05-19 06:23:05,137 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 06:23:05.137197
2025-05-19 06:33:04,810 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 06:33:04.810177
2025-05-19 06:39:20,875 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 06:39:20,890 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 06:39:23,956 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 06:39:23,958 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 06:39:32,543 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 06:39:33,744 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 06:43:04,824 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 06:43:04.824601
2025-05-19 06:53:04,807 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 06:53:04.807414
2025-05-19 07:03:04,866 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 07:03:04.866286
2025-05-19 07:13:04,873 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 07:13:04.871761
2025-05-19 07:23:04,829 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 07:23:04.829167
2025-05-19 07:33:04,825 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 07:33:04.825308
2025-05-19 07:39:33,852 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 07:39:33,878 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 07:39:36,716 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 07:39:36,719 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 07:39:44,236 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 07:39:46,527 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 07:43:04,813 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 07:43:04.813402
2025-05-19 07:53:04,849 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 07:53:04.849185
2025-05-19 08:03:04,820 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 08:03:04.820473
2025-05-19 08:13:04,873 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 08:13:04.873766
2025-05-19 08:23:04,825 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 08:23:04.825898
2025-05-19 08:33:04,843 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 08:33:04.843431
2025-05-19 08:39:46,544 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 08:39:46,546 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 08:39:49,495 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 08:39:49,497 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 08:39:55,925 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 08:39:58,754 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 08:43:04,828 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 08:43:04.828510
2025-05-19 08:53:04,807 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 08:53:04.807760
2025-05-19 09:03:04,835 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 09:03:04.835928
2025-05-19 09:13:04,840 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 09:13:04.840629
2025-05-19 09:23:04,841 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 09:23:04.841625
2025-05-19 09:33:04,869 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 09:33:04.869010
2025-05-19 09:39:58,768 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 09:39:58,771 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 09:40:04,417 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 09:40:04,419 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 09:40:09,972 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 09:40:14,605 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 09:43:04,861 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 09:43:04.861763
2025-05-19 09:53:04,861 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 09:53:04.861969
2025-05-19 10:03:04,864 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 10:03:04.864410
2025-05-19 10:13:04,878 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 10:13:04.878127
2025-05-19 10:23:04,835 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 10:23:04.835609
2025-05-19 10:33:04,846 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 10:33:04.845115
2025-05-19 10:40:14,622 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 10:40:14,624 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 10:40:17,566 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 10:40:17,567 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 10:40:23,897 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 10:40:26,954 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 10:43:04,845 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 10:43:04.845329
2025-05-19 10:53:04,843 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 10:53:04.843467
2025-05-19 11:03:06,464 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 11:03:06.464342
2025-05-19 11:13:04,828 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 11:13:04.828556
2025-05-19 11:23:04,897 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 11:23:04.897563
2025-05-19 11:33:04,818 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 11:33:04.818260
2025-05-19 11:40:26,956 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 11:40:26,967 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 11:40:34,587 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 11:40:34,600 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 11:40:38,805 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 11:40:46,473 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 11:43:04,824 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 11:43:04.824774
2025-05-19 11:53:04,872 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 11:53:04.872740
2025-05-19 12:03:04,836 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 12:03:04.836483
2025-05-19 12:13:04,857 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 12:13:04.857014
2025-05-19 12:23:04,854 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 12:23:04.854755
2025-05-19 12:33:04,938 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 12:33:04.938052
2025-05-19 12:41:03,639 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 12:41:03,642 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 12:41:11,521 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 12:41:11,525 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 12:41:18,642 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 12:41:21,789 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 12:43:04,893 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 12:43:04.893496
2025-05-19 12:53:04,858 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 12:53:04.858928
2025-05-19 13:03:04,891 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 13:03:04.891429
2025-05-19 13:13:04,860 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 13:13:04.860190
2025-05-19 13:23:04,883 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 13:23:04.883331
2025-05-19 13:33:04,892 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 13:33:04.892854
2025-05-19 13:41:21,795 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 13:41:21,797 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 13:41:30,088 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 13:41:30,092 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 13:41:36,582 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 13:41:40,049 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 13:43:04,875 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 13:43:04.875943
2025-05-19 13:53:04,884 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 13:53:04.884933
2025-05-19 14:03:04,874 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 14:03:04.874390
2025-05-19 14:13:04,815 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 14:13:04.815554
2025-05-19 14:23:04,816 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 14:23:04.816741
2025-05-19 14:33:04,843 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 14:33:04.843299
2025-05-19 14:41:40,064 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 14:41:40,067 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 14:41:42,681 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 14:41:42,683 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 14:41:49,231 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 14:41:51,736 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 14:43:04,844 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 14:43:04.844532
2025-05-19 14:53:04,839 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 14:53:04.838977
2025-05-19 15:03:04,947 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 15:03:04.947301
2025-05-19 15:13:04,840 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 15:13:04.840834
2025-05-19 15:23:04,859 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 15:23:04.859883
2025-05-19 15:33:04,843 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 15:33:04.843111
2025-05-19 15:41:51,742 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 15:41:51,744 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 15:41:54,357 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 15:41:54,359 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 15:42:01,436 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 15:42:04,711 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 15:43:04,832 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 15:43:04.832893
2025-05-19 15:53:04,831 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 15:53:04.831173
2025-05-19 16:03:04,836 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 16:03:04.836353
2025-05-19 16:13:04,840 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 16:13:04.840962
2025-05-19 16:23:04,882 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 16:23:04.882681
2025-05-19 16:33:04,855 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 16:33:04.855643
2025-05-19 16:42:04,724 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 16:42:04,744 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 16:42:15,275 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 16:42:15,294 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 16:42:21,425 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 16:42:24,086 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 16:43:05,178 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 16:43:05.178804
2025-05-19 16:53:04,848 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 16:53:04.848203
2025-05-19 17:03:05,069 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 17:03:05.069270
2025-05-19 17:13:04,977 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 17:13:04.977613
2025-05-19 17:23:04,834 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 17:23:04.834282
2025-05-19 17:33:04,863 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 17:33:04.863272
2025-05-19 17:42:41,033 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 17:42:41,035 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 17:42:43,434 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 17:42:43,437 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 17:42:50,205 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 17:42:52,720 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 17:43:04,827 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 17:43:04.827958
2025-05-19 17:53:04,967 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 17:53:04.967993
2025-05-19 18:03:04,822 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 18:03:04.822517
2025-05-19 18:13:04,818 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 18:13:04.818818
2025-05-19 18:23:04,815 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 18:23:04.815211
2025-05-19 18:33:04,839 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 18:33:04.839489
2025-05-19 18:42:52,722 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 18:42:52,724 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 18:42:55,681 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 18:42:55,682 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 18:43:01,692 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 18:43:04,849 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 18:43:04.849796
2025-05-19 18:43:04,960 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 18:53:04,813 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 18:53:04.813208
2025-05-19 19:00:00,034 [ERROR] [MainThread] [root/home.py:76]: The system cannot find the file specified: 'C:\Users\amn\Pictures'
2025-05-19 19:00:03,995 [ERROR] [MainThread] [root/home.py:76]: The system cannot find the file specified: 'C:\Users\amn\Pictures'
2025-05-19 19:03:04,852 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 19:03:04.851895
2025-05-19 19:09:35,005 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-19 19:09:35,112 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-19 19:09:35,112 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-19 19:09:35,139 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-19 19:09:35,143 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-19 19:09:35,145 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-19 19:09:35,213 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x0000021D2A5A36B0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-19 19:09:37,925 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-19 19:09:37,927 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-19 19:09:37,927 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-19 19:09:39,174 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-19 19:09:42,858 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-19 19:09:44,702 [INFO] [Dummy-3] [root/event_listener.py:53]: Created named pipe yasb-5a261db5-3506-11f0-90cf-346f24c928cb
2025-05-19 19:09:44,702 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-19 19:09:44,820 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-5a261db5-3506-11f0-90cf-346f24c928cb
2025-05-19 19:09:44,840 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-19 19:09:44,841 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 19:09:45,307 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 19:09:45.307195
2025-05-19 19:09:45,629 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:09:45,630 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:10:31,936 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-19 19:10:32,046 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-19 19:10:32,046 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-19 19:10:32,053 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-19 19:10:32,061 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-19 19:10:32,062 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-19 19:10:32,302 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-19 19:10:32,302 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-19 19:10:32,303 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-19 19:10:32,656 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-19 19:10:33,021 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-19 19:10:33,735 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-19 19:10:33,748 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-776043de-3506-11f0-a9e5-346f24c928cb
2025-05-19 19:10:33,783 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-19 19:10:33,786 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 19:10:33,845 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-776043de-3506-11f0-a9e5-346f24c928cb
2025-05-19 19:10:34,038 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 19:10:34.038539
2025-05-19 19:10:34,297 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:10:34,301 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:11:56,510 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-19 19:11:56,617 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-19 19:11:56,617 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-19 19:11:56,625 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-19 19:11:56,633 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-19 19:11:56,636 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-19 19:11:56,662 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000001701B16F6B0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-19 19:11:56,662 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of ActiveLayoutWidget object at 0x000001701B1BC050>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-19 19:11:56,880 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-19 19:11:56,880 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-19 19:11:56,881 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-19 19:11:57,278 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-19 19:11:57,740 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-19 19:11:58,491 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-19 19:11:58,491 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-a9e4cbd4-3506-11f0-9c4e-346f24c928cb
2025-05-19 19:11:58,542 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-19 19:11:58,544 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 19:11:58,596 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-a9e4cbd4-3506-11f0-9c4e-346f24c928cb
2025-05-19 19:11:58,731 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 19:11:58.731374
2025-05-19 19:11:59,076 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:11:59,095 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:12:13,520 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-19 19:12:13,621 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-19 19:12:13,621 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-19 19:12:13,630 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-19 19:12:13,636 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-19 19:12:13,638 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-19 19:12:13,679 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of ActiveLayoutWidget object at 0x000001C5D9CCCCD0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-19 19:12:13,679 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000001C5D9D0D310>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-19 19:12:13,878 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-19 19:12:13,878 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-19 19:12:13,878 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-19 19:12:14,254 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-19 19:12:14,620 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-19 19:12:15,388 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-19 19:12:15,401 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-b3f6fec5-3506-11f0-bbf9-346f24c928cb
2025-05-19 19:12:15,449 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-19 19:12:15,452 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-19 19:12:15,529 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-b3f6fec5-3506-11f0-bbf9-346f24c928cb
2025-05-19 19:12:15,545 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 19:12:15.545351
2025-05-19 19:12:15,999 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:12:16,004 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:22:14,931 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 19:22:14.930406
2025-05-19 19:32:15,831 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 19:32:15.831368
2025-05-19 19:42:15,000 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 19:42:14.999705
2025-05-19 19:43:04,967 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:43:04,969 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:43:07,708 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:43:07,709 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:43:14,360 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:43:17,316 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 19:52:14,939 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 19:52:14.937787
2025-05-19 20:02:14,945 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 20:02:14.945390
2025-05-19 20:12:15,154 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 20:12:15.154986
2025-05-19 20:22:14,902 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 20:22:14.902958
2025-05-19 20:32:15,062 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 20:32:15.062841
2025-05-19 20:42:16,661 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 20:42:16.661775
2025-05-19 20:43:18,990 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 20:43:18,991 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 20:43:21,711 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 20:43:21,713 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 20:43:28,036 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 20:43:31,518 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 20:52:16,600 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 20:52:16.600939
2025-05-19 21:02:16,583 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 21:02:16.583653
2025-05-19 21:12:16,613 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 21:12:16.613232
2025-05-19 21:22:16,602 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 21:22:16.602669
2025-05-19 21:32:16,608 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 21:32:16.608285
2025-05-19 21:42:16,629 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 21:42:16.629535
2025-05-19 21:43:31,529 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 21:43:31,531 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 21:43:34,579 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 21:43:34,580 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 21:43:40,474 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 21:43:45,052 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 21:52:16,806 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 21:52:16.806466
2025-05-19 22:02:16,560 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 22:02:16.560141
2025-05-19 22:12:16,581 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 22:12:16.581069
2025-05-19 22:22:16,616 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 22:22:16.616385
2025-05-19 22:32:16,589 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 22:32:16.589272
2025-05-19 22:42:16,577 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 22:42:16.577255
2025-05-19 22:43:45,062 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 22:43:45,064 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 22:43:47,693 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 22:43:47,695 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 22:43:54,017 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 22:43:57,946 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 22:52:16,592 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 22:52:16.592191
2025-05-19 23:02:16,618 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 23:02:16.618173
2025-05-19 23:12:16,571 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 23:12:16.571933
2025-05-19 23:22:16,559 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 23:22:16.559555
2025-05-19 23:32:16,621 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 23:32:16.621186
2025-05-19 23:42:16,600 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 23:42:16.600115
2025-05-19 23:43:57,959 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 23:43:57,960 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 23:44:00,690 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 23:44:00,692 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 23:44:07,022 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 23:44:10,163 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-19 23:52:16,626 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-19 23:52:16.626875
2025-05-20 00:02:16,593 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 00:02:16.593405
2025-05-20 00:12:16,599 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 00:12:16.599668
2025-05-20 00:22:16,568 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 00:22:16.568595
2025-05-20 00:32:16,594 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 00:32:16.594449
2025-05-20 00:42:16,613 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 00:42:16.613764
2025-05-20 00:44:10,180 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 00:44:10,182 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 00:44:12,797 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 00:44:12,799 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 00:44:19,901 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 00:44:22,732 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 00:52:16,682 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 00:52:16.682924
2025-05-20 01:02:16,613 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 01:02:16.613217
2025-05-20 01:12:16,560 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 01:12:16.560082
2025-05-20 01:22:16,660 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 01:22:16.660816
2025-05-20 01:32:16,587 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 01:32:16.587265
2025-05-20 01:42:16,580 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 01:42:16.580839
2025-05-20 01:44:22,735 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 01:44:22,738 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 01:44:25,368 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 01:44:25,370 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 01:44:31,688 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 01:44:34,752 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 01:52:16,638 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 01:52:16.638697
2025-05-20 02:02:16,610 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 02:02:16.610201
2025-05-20 02:12:16,561 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 02:12:16.561087
2025-05-20 02:22:16,604 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 02:22:16.604527
2025-05-20 02:32:16,608 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 02:32:16.608349
2025-05-20 02:42:17,347 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 02:42:17.347436
2025-05-20 02:44:34,801 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 02:44:34,803 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 02:44:37,519 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 02:44:37,521 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 02:44:44,508 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 02:44:46,585 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 02:52:16,588 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 02:52:16.588072
2025-05-20 03:02:16,569 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 03:02:16.569408
2025-05-20 03:12:16,567 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 03:12:16.567732
2025-05-20 03:22:16,583 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 03:22:16.583661
2025-05-20 03:32:16,551 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 03:32:16.551424
2025-05-20 03:42:16,643 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 03:42:16.643738
2025-05-20 03:44:46,597 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 03:44:46,601 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 03:44:49,222 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 03:44:49,224 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 03:44:55,880 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 03:44:58,609 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 03:52:16,593 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 03:52:16.593168
2025-05-20 04:02:16,592 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 04:02:16.592229
2025-05-20 04:12:16,601 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 04:12:16.601772
2025-05-20 04:22:16,563 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 04:22:16.563884
2025-05-20 04:32:16,550 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 04:32:16.550406
2025-05-20 04:42:16,570 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 04:42:16.570531
2025-05-20 04:44:58,617 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 04:44:58,627 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 04:45:02,662 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 04:45:02,669 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 04:45:09,208 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 04:45:14,932 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 04:52:16,613 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 04:52:16.613505
2025-05-20 05:02:16,557 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 05:02:16.557764
2025-05-20 05:12:16,584 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 05:12:16.584085
2025-05-20 05:22:16,579 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 05:22:16.579608
2025-05-20 05:32:16,598 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 05:32:16.598740
2025-05-20 05:42:16,572 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 05:42:16.572961
2025-05-20 05:45:23,735 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 05:45:23,736 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 05:45:26,476 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 05:45:26,478 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 05:45:32,599 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 05:45:35,973 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 05:52:16,557 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 05:52:16.557537
2025-05-20 06:02:16,580 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 06:02:16.580828
2025-05-20 06:12:16,563 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 06:12:16.563950
2025-05-20 06:22:16,700 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 06:22:16.700364
2025-05-20 06:32:16,584 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 06:32:16.584711
2025-05-20 06:42:16,658 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 06:42:16.658959
2025-05-20 06:45:35,991 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 06:45:35,994 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 06:45:38,716 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 06:45:38,717 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 06:45:45,146 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 06:45:48,302 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 06:52:16,603 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 06:52:16.603780
2025-05-20 07:02:16,615 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 07:02:16.614103
2025-05-20 07:12:16,544 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 07:12:16.544969
2025-05-20 07:22:16,584 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 07:22:16.584225
2025-05-20 07:32:16,658 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 07:32:16.658672
2025-05-20 07:42:16,627 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 07:42:16.626071
2025-05-20 07:45:48,331 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 07:45:48,335 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 07:45:52,773 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 07:45:52,774 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 07:45:56,882 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 07:46:00,885 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 07:52:16,644 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 07:52:16.644964
2025-05-20 08:02:16,581 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 08:02:16.581235
2025-05-20 08:12:16,591 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 08:12:16.591426
2025-05-20 08:22:16,604 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 08:22:16.604345
2025-05-20 08:32:16,674 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 08:32:16.674919
2025-05-20 08:42:16,597 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 08:42:16.597923
2025-05-20 08:46:00,897 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 08:46:00,901 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 08:46:07,248 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 08:46:07,250 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 08:46:14,805 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 08:46:18,041 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 08:52:16,573 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 08:52:16.573531
2025-05-20 09:02:16,611 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 09:02:16.611326
2025-05-20 09:12:16,590 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 09:12:16.589209
2025-05-20 09:22:16,626 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 09:22:16.626457
2025-05-20 09:32:16,596 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 09:32:16.596413
2025-05-20 09:42:16,616 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 09:42:16.616068
2025-05-20 09:46:18,052 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 09:46:18,056 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 09:46:21,218 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 09:46:21,221 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 09:46:28,202 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 09:46:32,023 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 09:52:16,580 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 09:52:16.580119
2025-05-20 10:02:16,603 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 10:02:16.603255
2025-05-20 10:12:16,593 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 10:12:16.592444
2025-05-20 10:22:16,614 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 10:22:16.614769
2025-05-20 10:32:16,615 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 10:32:16.615840
2025-05-20 10:48:36,085 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 10:48:36.085284
2025-05-20 10:52:50,245 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 10:52:50,261 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 10:53:01,192 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 10:53:01,205 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 10:53:04,396 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 10:53:13,648 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 10:58:36,053 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 10:58:36.053356
2025-05-20 11:08:36,069 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 11:08:36.069542
2025-05-20 11:18:36,037 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 11:18:36.036253
2025-05-20 11:28:36,099 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 11:28:36.099037
2025-05-20 11:38:36,053 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 11:38:36.053162
2025-05-20 11:48:36,104 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 11:48:36.104723
2025-05-20 11:53:22,136 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 11:53:22,139 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 11:53:40,757 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 11:53:40,761 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 11:53:41,735 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 11:53:56,410 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 11:58:36,052 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 11:58:36.052903
2025-05-20 12:17:01,892 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 12:17:01.892314
2025-05-20 12:27:01,860 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 12:27:01.860952
2025-05-20 12:37:01,889 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 12:37:01.889218
2025-05-20 12:47:01,948 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 12:47:01.948214
2025-05-20 12:57:02,640 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 12:57:02.640090
2025-05-20 13:02:21,174 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 13:02:21,175 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 13:02:23,814 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 13:02:23,816 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 13:02:30,058 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 13:02:33,122 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 13:07:01,871 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 13:07:01.871929
2025-05-20 13:17:01,870 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 13:17:01.870581
2025-05-20 13:27:01,883 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 13:27:01.883630
2025-05-20 13:37:01,927 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 13:37:01.927546
2025-05-20 13:47:01,886 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 13:47:01.886096
2025-05-20 13:57:01,868 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 13:57:01.868329
2025-05-20 14:02:33,143 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 14:02:33,146 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 14:02:35,753 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 14:02:35,755 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 14:02:41,646 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 14:02:44,923 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 14:07:01,912 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 14:07:01.911959
2025-05-20 14:17:01,864 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 14:17:01.864616
2025-05-20 14:27:01,864 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 14:27:01.864177
2025-05-20 14:37:01,951 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 14:37:01.951392
2025-05-20 14:47:01,907 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 14:47:01.907633
2025-05-20 14:57:01,864 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 14:57:01.864060
2025-05-20 15:02:44,930 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 15:02:44,932 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 15:02:47,550 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 15:02:47,552 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 15:02:53,442 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 15:02:57,588 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 15:07:01,881 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 15:07:01.881406
2025-05-20 15:17:01,886 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 15:17:01.886249
2025-05-20 15:27:02,023 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 15:27:02.023588
2025-05-20 15:37:01,886 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 15:37:01.886546
2025-05-20 15:47:01,884 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 15:47:01.884789
2025-05-20 15:57:01,987 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 15:57:01.987877
2025-05-20 16:02:57,615 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 16:02:57,617 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 16:03:04,918 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 16:03:04,920 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 16:03:10,670 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 16:03:16,938 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 16:07:01,954 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 16:07:01.954333
2025-05-20 16:17:01,978 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 16:17:01.978983
2025-05-20 16:27:01,904 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 16:27:01.904867
2025-05-20 16:37:01,895 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 16:37:01.895538
2025-05-20 16:47:01,899 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 16:47:01.899620
2025-05-20 16:57:02,003 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 16:57:02.003319
2025-05-20 17:03:16,953 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 17:03:16,962 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 17:03:20,993 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 17:03:21,001 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 17:03:27,206 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 17:03:32,444 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 17:07:01,851 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 17:07:01.851272
2025-05-20 17:17:02,091 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 17:17:02.091798
2025-05-20 17:27:01,919 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 17:27:01.919436
2025-05-20 17:37:01,891 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 17:37:01.891444
2025-05-20 17:47:01,923 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 17:47:01.923877
2025-05-20 17:57:01,873 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 17:57:01.873307
2025-05-20 18:03:42,356 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 18:03:42,357 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 18:03:45,308 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 18:03:45,310 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 18:03:51,458 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 18:04:00,388 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 18:07:01,882 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 18:07:01.882716
2025-05-20 18:17:01,894 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 18:17:01.893662
2025-05-20 18:27:01,880 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 18:27:01.880494
2025-05-20 18:37:01,866 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 18:37:01.866490
2025-05-20 18:47:01,884 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 18:47:01.884960
2025-05-20 18:57:01,849 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 18:57:01.849484
2025-05-20 19:04:00,390 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 19:04:00,392 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 19:04:03,015 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 19:04:03,017 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 19:04:10,009 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 19:04:14,151 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 19:07:01,910 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 19:07:01.910067
2025-05-20 19:17:01,892 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 19:17:01.892932
2025-05-20 19:27:02,191 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 19:27:02.191646
2025-05-20 19:37:01,885 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 19:37:01.885639
2025-05-20 19:47:01,905 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 19:47:01.905120
2025-05-20 19:57:01,863 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 19:57:01.863390
2025-05-20 20:04:14,163 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 20:04:14,165 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 20:04:17,119 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 20:04:17,120 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 20:04:22,936 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 20:04:25,951 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 20:07:02,474 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 20:07:02.474684
2025-05-20 20:17:01,879 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 20:17:01.878486
2025-05-20 20:27:01,897 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 20:27:01.896755
2025-05-20 20:37:01,862 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 20:37:01.862419
2025-05-20 20:47:01,879 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 20:47:01.879898
2025-05-20 20:57:02,087 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 20:57:02.087233
2025-05-20 21:04:25,956 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 21:04:25,959 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 21:04:28,583 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 21:04:28,584 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 21:04:34,593 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 21:04:38,199 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 21:07:01,882 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 21:07:01.882268
2025-05-20 21:17:01,946 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 21:17:01.946865
2025-05-20 21:27:01,879 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 21:27:01.879411
2025-05-20 21:37:01,890 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 21:37:01.890600
2025-05-20 21:47:01,899 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 21:47:01.899665
2025-05-20 21:57:01,887 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 21:57:01.887328
2025-05-20 22:04:38,203 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:04:38,207 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:04:40,841 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:04:40,842 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:04:46,840 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:04:50,319 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:07:01,931 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:07:01.931435
2025-05-20 22:17:01,928 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:17:01.928980
2025-05-20 22:27:01,992 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:27:01.992873
2025-05-20 22:37:01,927 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:37:01.927572
2025-05-20 22:37:05,478 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:37:05,589 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:37:05,589 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:37:05,615 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:37:05,621 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:37:05,626 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:37:08,343 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:37:08,343 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:37:08,344 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:37:09,645 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:37:14,355 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:37:15,997 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:37:16,020 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-821cd0af-35ec-11f0-aa98-346f24c928cb
2025-05-20 22:37:16,097 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:37:16,098 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:37:16,190 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:37:16.189303
2025-05-20 22:37:16,924 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:37:16,927 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:38:08,135 [INFO] [MainThread] [root/controller.py:12]: Reloading Application from tray...
2025-05-20 22:38:08,245 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:38:08,245 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:38:08,252 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:38:08,260 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:38:08,261 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:38:08,539 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:38:08,539 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:38:08,540 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:38:08,765 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:38:09,111 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:38:09,762 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:38:09,791 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-a228c218-35ec-11f0-b128-346f24c928cb
2025-05-20 22:38:09,830 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:38:09,831 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:38:09,909 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-a228c218-35ec-11f0-b128-346f24c928cb
2025-05-20 22:38:10,011 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:38:10.011156
2025-05-20 22:38:10,349 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:38:10,362 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:38:28,630 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:38:28,740 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:38:28,740 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:38:28,746 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:38:28,756 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:38:28,757 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:38:28,993 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:38:28,994 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:38:28,994 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:38:29,313 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:38:29,655 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:38:30,229 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:38:30,244 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-ae5be188-35ec-11f0-b174-346f24c928cb
2025-05-20 22:38:30,283 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:38:30,285 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:38:30,344 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-ae5be188-35ec-11f0-b174-346f24c928cb
2025-05-20 22:38:30,474 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:38:30.474295
2025-05-20 22:38:30,788 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:38:30,792 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:38:49,406 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:38:49,520 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:38:49,520 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:38:49,527 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:38:49,535 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:38:49,538 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:38:49,581 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x0000012314CBF6B0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-20 22:38:49,582 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of ActiveLayoutWidget object at 0x0000012314D0C050>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-20 22:38:49,784 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:38:49,785 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:38:49,785 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:38:50,103 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:38:50,460 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:38:51,020 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:38:51,033 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-bac051be-35ec-11f0-b675-346f24c928cb
2025-05-20 22:38:51,067 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:38:51,068 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:38:51,152 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-bac051be-35ec-11f0-b675-346f24c928cb
2025-05-20 22:38:51,286 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:38:51.286437
2025-05-20 22:38:51,585 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:38:51,588 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:39:09,639 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:39:09,747 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:39:09,747 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:39:09,755 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:39:09,764 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:39:09,766 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:39:09,785 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000002A51DE0F6B0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-20 22:39:10,011 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:39:10,012 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:39:10,012 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:39:10,312 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:39:10,636 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:39:11,228 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:39:11,242 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-c6cbd134-35ec-11f0-83c4-346f24c928cb
2025-05-20 22:39:11,276 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:39:11,278 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:39:11,335 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:39:11.335979
2025-05-20 22:39:11,357 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-c6cbd134-35ec-11f0-83c4-346f24c928cb
2025-05-20 22:39:11,784 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:39:11,788 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:39:38,962 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:39:39,072 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:39:39,072 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:39:39,078 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:39:39,088 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:39:39,090 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:39:39,133 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000001D91304F6B0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-20 22:39:39,133 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of ActiveLayoutWidget object at 0x000001D91309C050>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-20 22:39:39,325 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:39:39,325 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:39:39,326 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:39:39,617 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:39:39,997 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:39:40,605 [INFO] [Dummy-3] [root/event_listener.py:53]: Created named pipe yasb-d84e5c7a-35ec-11f0-9bab-346f24c928cb
2025-05-20 22:39:40,606 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:39:40,666 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:39:40,669 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:39:40,744 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-d84e5c7a-35ec-11f0-9bab-346f24c928cb
2025-05-20 22:39:40,851 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:39:40.851035
2025-05-20 22:39:41,228 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:39:41,232 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:39:50,537 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:39:50,648 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:39:50,648 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:39:50,656 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:39:50,664 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:39:50,665 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:39:50,966 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:39:50,968 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:39:50,968 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:39:51,205 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:39:51,547 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:39:52,159 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:39:52,159 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-df314033-35ec-11f0-b013-346f24c928cb
2025-05-20 22:39:52,207 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:39:52,208 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:39:52,274 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-df314033-35ec-11f0-b013-346f24c928cb
2025-05-20 22:39:52,315 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:39:52.315931
2025-05-20 22:39:52,722 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:39:52,731 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:43:55,832 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:43:55,933 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:43:55,933 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:43:55,941 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:43:55,948 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:43:55,950 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:43:56,195 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:43:56,195 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:43:56,196 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:43:56,513 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:43:56,900 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:43:57,581 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:43:57,593 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-7179bd59-35ed-11f0-a9de-346f24c928cb
2025-05-20 22:43:57,630 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:43:57,634 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:43:57,714 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-7179bd59-35ed-11f0-a9de-346f24c928cb
2025-05-20 22:43:57,913 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:43:57.913270
2025-05-20 22:43:58,173 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:43:58,186 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:52:21,687 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:52:21,788 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:52:21,788 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:52:21,794 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:52:21,805 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:52:21,806 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:52:21,834 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x00000252DB9BF6B0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-20 22:52:22,045 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:52:22,046 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:52:22,046 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:52:22,363 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:52:22,699 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:52:23,281 [INFO] [Dummy-3] [root/event_listener.py:53]: Created named pipe yasb-9ee56813-35ee-11f0-9ba9-346f24c928cb
2025-05-20 22:52:23,291 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:52:23,340 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:52:23,341 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:52:23,400 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-9ee56813-35ee-11f0-9ba9-346f24c928cb
2025-05-20 22:52:23,609 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:52:23.609033
2025-05-20 22:52:23,870 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:52:23,875 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:54:31,766 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:54:31,878 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:54:31,878 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:54:31,884 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:54:31,894 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:54:31,895 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:54:32,140 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:54:32,140 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:54:32,141 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:54:32,436 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:54:32,787 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:54:33,356 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:54:33,368 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-ec6d3e75-35ee-11f0-a910-346f24c928cb
2025-05-20 22:54:33,404 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:54:33,406 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:54:33,467 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-ec6d3e75-35ee-11f0-a910-346f24c928cb
2025-05-20 22:54:33,670 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:54:33.670940
2025-05-20 22:54:33,909 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:54:33,923 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:55:00,936 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:55:01,041 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:55:01,041 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:55:01,048 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:55:01,056 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:55:01,058 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:55:01,107 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x000001CE137AB750>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-20 22:55:01,315 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:55:01,315 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:55:01,315 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:55:01,633 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:55:01,947 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:55:02,574 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:55:02,585 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-fdd7848e-35ee-11f0-a8b5-346f24c928cb
2025-05-20 22:55:02,620 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:55:02,621 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:55:02,674 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:55:02.674698
2025-05-20 22:55:02,692 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-fdd7848e-35ee-11f0-a8b5-346f24c928cb
2025-05-20 22:55:03,117 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:55:03,121 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:55:40,950 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:55:41,064 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:55:41,064 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:55:41,070 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:55:41,079 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:55:41,084 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:55:41,323 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:55:41,323 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:55:41,324 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:55:41,630 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:55:41,975 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:55:42,025 [WARNING] [MainThread] [root/widget_builder.py:38]: No widget config could be found for widget 'wallpapers
2025-05-20 22:55:42,541 [INFO] [Dummy-3] [root/event_listener.py:53]: Created named pipe yasb-15aa1776-35ef-11f0-96e7-346f24c928cb
2025-05-20 22:55:42,552 [ERROR] [MainThread] [root/widget_builder.py:77]: Failed to add undefined widget(s)  - The widget "wallpapers" is undefined.
2025-05-20 22:55:42,733 [INFO] [Dummy-3] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-15aa1776-35ef-11f0-96e7-346f24c928cb
2025-05-20 22:55:43,034 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:55:43.034804
2025-05-20 22:55:43,319 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:55:43,325 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:55:50,062 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:56:04,126 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:56:04,128 [DEBUG] [Dummy-10] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:56:04,152 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:56:04,257 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:56:04,257 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:56:04,398 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:56:04,414 [DEBUG] [Dummy-10] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:56:04,416 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:56:04,652 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:56:04,652 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:56:04,653 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:56:04,988 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:56:05,316 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:56:06,079 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:56:06,093 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-23b1c3cf-35ef-11f0-9138-346f24c928cb
2025-05-20 22:56:06,128 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:56:06,129 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:56:06,198 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:56:06.198855
2025-05-20 22:56:06,210 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-23b1c3cf-35ef-11f0-9138-346f24c928cb
2025-05-20 22:56:06,658 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:56:06,669 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:58:12,926 [ERROR] [MainThread] [root/home.py:76]: The system cannot find the file specified: 'C:\Users\amn\Pictures'
2025-05-20 22:58:15,599 [ERROR] [MainThread] [root/home.py:76]: The system cannot find the file specified: 'C:\Users\amn\Pictures'
2025-05-20 22:59:24,996 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 22:59:25,096 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 22:59:25,096 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 22:59:25,129 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 22:59:25,143 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 22:59:25,146 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 22:59:25,385 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 22:59:25,385 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 22:59:25,385 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 22:59:25,703 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 22:59:26,055 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 22:59:26,703 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 22:59:26,703 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-9b467c70-35ef-11f0-bf4d-346f24c928cb
2025-05-20 22:59:26,753 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 22:59:26,754 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 22:59:26,802 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-9b467c70-35ef-11f0-bf4d-346f24c928cb
2025-05-20 22:59:27,062 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 22:59:27.062971
2025-05-20 22:59:27,255 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:59:27,265 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 22:59:39,606 [ERROR] [MainThread] [root/home.py:76]: The system cannot find the file specified: 'C:\Downloads'
2025-05-20 23:00:41,109 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 23:00:41,212 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 23:00:41,212 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 23:00:41,219 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 23:00:41,228 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 23:00:41,231 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 23:00:41,288 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of WorkspaceWidget object at 0x0000021F6F0DF6B0>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-20 23:00:41,289 [ERROR] [Dummy-5] [root/event_service.py:30]: Failed to emit signal <bound PYQT_SIGNAL k_signal_update of ActiveLayoutWidget object at 0x0000021F6F12C050>. Removing link to KomorebiEvent.KomorebiUpdate.
2025-05-20 23:00:41,478 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 23:00:41,479 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 23:00:41,479 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 23:00:41,848 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 23:00:42,247 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 23:00:42,913 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 23:00:42,913 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-c8b3383a-35ef-11f0-89f1-346f24c928cb
2025-05-20 23:00:42,964 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 23:00:42,966 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 23:00:43,064 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-c8b3383a-35ef-11f0-89f1-346f24c928cb
2025-05-20 23:00:43,258 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 23:00:43.258206
2025-05-20 23:00:43,524 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 23:00:43,526 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 23:00:49,474 [ERROR] [MainThread] [root/home.py:76]: The system cannot find the file specified: 'C:\Downloads'
2025-05-20 23:00:53,634 [ERROR] [MainThread] [root/home.py:76]: The system cannot find the file specified: 'C:\Downloads'
2025-05-20 23:01:33,914 [INFO] [MainThread] [root/controller.py:12]: Reloading Application because of config update...
2025-05-20 23:01:34,021 [INFO] [MainThread] [cli_server/cli_server.py:112]: Log pipe server stopped
2025-05-20 23:01:34,021 [DEBUG] [MainThread] [cli_server/cli_server.py:206]: CLI server stopped
2025-05-20 23:01:34,027 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:218]: Stopping worker thread...
2025-05-20 23:01:34,037 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:201]: Exiting thread
2025-05-20 23:01:34,040 [DEBUG] [MainThread] [qasync._windows._IocpProactor/_windows.py:75]: Closing
2025-05-20 23:01:34,285 [INFO] [MainThread] [root/log.py:59]: Yasb v1.7.4
2025-05-20 23:01:34,286 [INFO] [Thread-1 (_run_server)] [cli_server/cli_server.py:212]: CLI server started v1.1.1
2025-05-20 23:01:34,286 [INFO] [MainThread] [cli_server/cli_server.py:104]: Log pipe server started
2025-05-20 23:01:34,611 [DEBUG] [MainThread] [tzlocal/win32.py:55]: Looking up time zone info from registry
2025-05-20 23:01:35,176 [DEBUG] [MainThread] [comtypes/__init__.py:149]: CoInitializeEx(None, 2)
2025-05-20 23:01:36,081 [INFO] [MainThread] [root/watcher.py:55]: Created file watcher for path C:\Users\zhiyu\.config\yasb
2025-05-20 23:01:36,082 [INFO] [Dummy-5] [root/event_listener.py:53]: Created named pipe yasb-e8640fb9-35ef-11f0-8029-346f24c928cb
2025-05-20 23:01:36,158 [DEBUG] [MainThread] [qasync._windows._EventPoller/_windows.py:213]: Starting (proactor: <_IocpProactor overlapped#=0 result#=0>)...
2025-05-20 23:01:36,160 [DEBUG] [Dummy-8] [qasync._windows._EventWorker/_windows.py:192]: Thread started
2025-05-20 23:01:36,271 [INFO] [Dummy-5] [root/event_listener.py:125]: Komorebi connected to named pipe: yasb-e8640fb9-35ef-11f0-8029-346f24c928cb
2025-05-20 23:01:36,350 [INFO] [MainThread] [root/weather.py:67]: Fetching new weather data at 2025-05-20 23:01:36.350167
2025-05-20 23:01:36,693 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 23:01:36,699 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 23:04:50,426 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 23:04:50,428 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 23:04:53,400 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 23:04:53,402 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 23:05:00,375 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
2025-05-20 23:05:02,773 [DEBUG] [TrayMonitorThread] [root/utils.py:42]: Could not open process with PID 0
